config/routes.rb
Rails.application.routes.draw do
  resources :colorschemas

  resources :dotfiles

  resources :hacks
  get 'hacks_tags/:tag', to: 'hacks#index', as: :hacks_tags
  get 'hacks_vote/:id', to: 'hacks#vote', as: :hacks_vote

  devise_for :users
  resources :users
  get 'view_log', to: 'users#view_log', as: :log
  get 'view_plugins_list', to: 'users#view_plugins_list', as: :plugins_list
  post 'create_dotfile', to: 'users#create_dotfile', as: :create_dotfile

  resources :posts
  get 'posts_tags/:tag', to: 'posts#index', as: :posts_tags

  resources :plugins
  get 'plugins_tags/:tag', to: 'plugins#index', as: :plugins_tags
  get 'plugins_vote/:id', to: 'plugins#vote', as: :plugins_vote

  get 'search', to: 'search#search', as: :search
  match "/auth/:provider/callback" => "sessions#create", via: [:get]

  root 'users#index'

end

app/models/hack.rb
# == Schema Information
#
# Table name: hacks
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  body       :text             not null
#  user_id    :integer          not null
#  slug       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#  popularity :integer          default(0)
#

class Hack < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:title, :body]

	validates_presence_of :title
	validates_presence_of :body

	belongs_to :user
	acts_as_taggable

	extend FriendlyId
	friendly_id :slug_title, use: :slugged

	def slug_title
		[
			:title,
			[:title, Random.rand(1..10)],
			[:title, Random.rand(10.99)]
		]
	end

	def should_generate_new_friendly_id?
		title_changed? || slug.blank?
	end

	# метод отвечающий за рейтинг хака
	def self.vote(hack, current_user)
 	  # увеличиваем на 1 рейтинг хака и записываем в массив id текущего пользователя только один раз
    unless current_user.hack_id.include?(hack.id)
      hack.increment!(:popularity)
      current_user.hack_id += [hack.id]
    end
    current_user.save(validate: false)
	end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_action :set_hack, only: [:show, :edit, :update, :destroy, :vote]
  before_action :give_access_to_edit_record, only: [:edit, :update, :destroy]

  def index
    # Этот метод из application_controller.rb, предназначен для отображения количества используемых
    # в данной модели тэгов, в качестве аргумента передается название модели с заглавной буквы
    work_with_tags(:Hack)
    if params[:tag]
      @hacks = Hack.tagged_with(params[:tag])
    else
      @hacks = Hack.order('popularity DESC')
    end
  end

  def show
  end

  def new
    @hack = Hack.new
  end

  def edit
  end

  def create
    @hack = current_user.hacks.new(hack_params)
    if @hack.save
      flash[:success] = "Hack was successfully created"
      redirect_to @hack
    else
      flash[:error] = "Hack was not created"
      render :new
    end
  end

  def update
    if @hack.update(hack_params)
      redirect_to @hack
    else
      render :edit
    end
  end

  def destroy
    @hack.destroy
    redirect_to hacks_path
  end

  # метод, отвечающий за рейтинг хака
  def vote
    Hack.vote(@hack, current_user)
    redirect_to hacks_path
  end

  private

    def set_hack
      @hack = Hack.friendly.find(params[:id])
    end

    def hack_params
      params.require(:hack).permit(:title, :body, :tag_list, :tag, :slug, :popularity)
    end

    # даем разрешение на редактирование и удаление записей только админам, модераторам и создателям этой записи
    def give_access_to_edit_record
      check_permissions(@hack)
    end
end

app/views/hacks/_form.html.slim
= form_for @hack do |f|
  - if @hack.errors.any?
    #error_explanation
      h2 = "#{pluralize(@hack.errors.count, "error")} prohibited this hack from being saved:"
      ul
        - @hack.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :tag
    = f.text_field :tag_list
  .actions = f.submit 'Save'

app/views/hacks/edit.html.slim
h1 Editing hack

== render 'form'

= link_to 'Show', @hack
'|
= link_to 'Back', hacks_path

app/views/hacks/index.html.slim
h1 Listing hacks

- @hacks.find_all do |hack|
  | title:&nbsp
  strong = link_to hack.title, hack_path(hack)
  | &nbsp tag:&nbsp
  strong = raw hack.tag_list.map { |t| link_to t, hacks_tags_path(t) }.join(', ')
  | &nbsp delete?:&nbsp
  strong = link_to 'Delete', hack, method: :delete, data: { confirm: "You sure?" }   
  - unless current_user.nil? || current_user.hack_id.include?(hack.id)  
    | &nbsp like?:&nbsp
    = link_to 'Vote', hacks_vote_path(hack)

  br

  br

br

- @tag_statistic.each do |tag_name, count|
  = link_to tag_name, hacks_tags_path(tag_name)
  | &nbsp&nbsp
  = count
  br

= link_to 'New Hack', new_hack_path

br

app/views/hacks/new.html.slim
h1 New hack

== render 'form'

= link_to 'Back', hacks_path

app/views/hacks/show.html.slim
p#notice = notice

p
  strong Title:
  = @hack.title
p
  strong Body:
  = @hack.body

= link_to 'Back', request.referer