config/routes.rb
Rails.application.routes.draw do
  resources :colorschemas

  resources :dotfiles

  resources :hacks
  get 'hacks_tags/:tag', to: 'hacks#index', as: :hacks_tags
  get 'hacks_vote/:id', to: 'hacks#vote', as: :hacks_vote

  devise_for :users
  resources :users
  get 'view_log', to: 'users#view_log', as: :log
  get 'view_plugins_list', to: 'users#view_plugins_list', as: :plugins_list
  post 'create_dotfile', to: 'users#create_dotfile', as: :create_dotfile

  resources :posts
  get 'posts_tags/:tag', to: 'posts#index', as: :posts_tags

  resources :plugins
  get 'plugins_tags/:tag', to: 'plugins#index', as: :plugins_tags
  get 'plugins_vote/:id', to: 'plugins#vote', as: :plugins_vote

  get 'search', to: 'search#search', as: :search
  match "/auth/:provider/callback" => "sessions#create", via: [:get]

  root 'users#index'

end

app/models/plugin.rb
# == Schema Information
#
# Table name: plugins
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  description :string(255)      not null
#  link        :string(255)      not null
#  user_id     :integer          not null
#  slug        :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#  popularity  :integer          default(0)
#

class Plugin < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:title, :description]

	validates_presence_of :title
	validates_presence_of :description
	validates_presence_of :link

	belongs_to :user
	acts_as_taggable

	extend FriendlyId
	friendly_id :slug_title, use: :slugged

	def slug_title
		[
			:title,
			[:title, Random.rand(1..10)],
			[:title, Random.rand(10.99)]
		]
	end

	def should_generate_new_friendly_id?
		title_changed? || slug.blank?
	end

	private

	# метод, отвечающий за рейтинг плагина
  def self.vote(plugin, current_user)
    # увеличиваем на 1 рейтинг плагина и записываем в массив id текущего пользователя только один раз
    unless current_user.plugin_id.include?(plugin.id)
      plugin.increment!(:popularity)
      current_user.plugin_id += [plugin.id]
    end
    current_user.save(validate: false)
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  before_action :set_plugin, only: [:show, :edit, :update, :destroy, :vote]
  before_action :give_access_to_edit_record, only: [:edit, :update, :destroy]

  def index
    # Этот метод из application_controller.rb, предназначен для отображения количества используемых
    # в данной модели тэгов, в качестве аргумента передается название модели с заглавной буквы
    work_with_tags(:Plugin)
    if params[:tag]
      @plugins = Plugin.tagged_with(params[:tag])
    else
      @plugins = Plugin.order('popularity DESC')
    end
  end

  def show
  end

  def new
    @plugin = Plugin.new
  end

  def edit
  end

  def create
    @plugin = current_user.plugins.new(plugin_params)
    if @plugin.save
      flash[:success] = "Plugin was successfully created"
      redirect_to @plugin
    else
      flash[:error] = "Plugin was not created"
      render :new
    end
  end

  def update
    if @plugin.update(plugin_params)
      redirect_to @plugin
    else
      render :edit
    end
  end

  def destroy
    @plugin.destroy
    redirect_to plugins_path
  end

  # метод, отвечающий за рейтинг плагина
  def vote
    Plugin.vote(@plugin, current_user)
    redirect_to plugins_path
  end

  private

    def set_plugin
      @plugin = Plugin.friendly.find(params[:id])
    end

    def plugin_params
      params.require(:plugin).permit(:title, :description, :link, :tag_list, :tag, :slug, :popularity)
    end

    def give_access_to_edit_record
      check_permissions(@plugin)
    end
  end

app/views/plugins/_form.html.slim
= form_for(@plugin) do |f|
  - if @plugin.errors.any?
    #error_explanation
      h2 = "#{pluralize(@plugin.errors.count, "error")} prohibited this colorschema from being saved:"
      ul
        - @plugin.errors.full_messages.each do |message|
          li = message

  .field
  = f.label :title
  p
  = f.text_field :title
  br
  .field
  = f.label :description
  p
  = f.text_area :description, placeholder: "Enter descroption"
  br
  .field
  = f.label :link
  p
  = f.text_field :link, placeholder: "Enter link"
  br
  .field
  = f.label :tag
  p
  = f.text_field :tag_list, placeholder: "Enter title"

  .actions
  = f.submit

app/views/plugins/edit.html.slim
h1 Editing plugin

= render 'form'

= link_to 'Show', @plugin 
|  || 
= link_to 'Back', plugins_path

app/views/plugins/index.html.slim
h1 Listing plugins

- @plugins.find_all do |plugin|
  | title:&nbsp
  strong = link_to plugin.title, plugin_path(plugin)
  | &nbsp tag:&nbsp
  strong = raw plugin.tag_list.map { |t| link_to t, plugins_tags_path(t) }.join(', ')
  | &nbsp delete?:&nbsp
  strong = link_to 'Delete', plugin, method: :delete, data: { confirm: "You sure?" } 
  - unless current_user.nil? || current_user.plugin_id.include?(plugin.id)
    | &nbsp like?&nbsp
    = link_to 'Vote', plugins_vote_path(plugin)
  br

  br

br

- @tag_statistic.each do |tag_name, count|
  = link_to tag_name, plugins_tags_path(tag_name)
  | &nbsp&nbsp
  = count
  br

= link_to 'New Plugin', new_plugin_path


br

app/views/plugins/new.html.slim
h1 New plugin

= render 'form'

= link_to 'Back', plugins_path

app/views/plugins/show.html.slim
h3 Title: 
= @plugin.title
h3 Description: 
= @plugin.description
h3 Link: 
= @plugin.link
br
br

= link_to 'Back', request.referer