config/routes.rb
Rails.application.routes.draw do
  resources :colorschemas

  resources :dotfiles

  resources :hacks
  get 'hacks_tags/:tag', to: 'hacks#index', as: :hacks_tags
  get 'hacks_vote/:id', to: 'hacks#vote', as: :hacks_vote

  devise_for :users
  resources :users
  get 'view_log', to: 'users#view_log', as: :log
  get 'view_plugins_list', to: 'users#view_plugins_list', as: :plugins_list
  post 'create_dotfile', to: 'users#create_dotfile', as: :create_dotfile

  resources :posts
  get 'posts_tags/:tag', to: 'posts#index', as: :posts_tags

  resources :plugins
  get 'plugins_tags/:tag', to: 'plugins#index', as: :plugins_tags
  get 'plugins_vote/:id', to: 'plugins#vote', as: :plugins_vote

  get 'search', to: 'search#search', as: :search
  match "/auth/:provider/callback" => "sessions#create", via: [:get]

  root 'users#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  body       :string(255)      not null
#  user_id    :integer          not null
#  post_img   :string(255)      default("")
#  slug       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:title, :body]

	validates_presence_of :title
	validates_presence_of :body

	belongs_to :user
	acts_as_taggable

	mount_uploader :post_img, PostsImgUploader

	extend FriendlyId
	friendly_id :slug_title, use: :slugged

	def slug_title
		[
			:title,
			[:title, Random.rand(1..10)],
			[:title, Random.rand(10.99)]
		]
	end

	def should_generate_new_friendly_id?
		title_changed? || slug.blank?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :give_access_to_edit_record, only: [:edit, :update, :destroy]

	def index
    # Этот метод из application_controller.rb, предназначен для отображения количества используемых
    # в данной модели тэгов, в качестве аргумента передается название модели с заглавной буквы
    work_with_tags(:Post)
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
		  @posts = Post.all
    end
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "Post was successfully created"
      redirect_to @post
    else
      flash[:error] = "Post was not created"
      render :new
    end
	end

	def edit
	end

	def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
	end

	def destroy
    @post.destroy
    redirect_to posts_path
	end

  private

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(current_user.id, :title, :body, :tag_list, :tag, :post_img, :post_img_cache, :slug)
    end

    # даем разрешение на редактирование и удаление записей только админам, модераторам и создателям этой записи
    def give_access_to_edit_record
      check_permissions(@post)
    end
  end

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this colorschema from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .textfield
  = f.text_field :title, placeholder: "Enter title"
  br

  = f.text_area :body, placeholder: "Enter text"
  br

  .textfield
  = f.text_field :tag_list, placeholder: "Enter tag"
  br

  = f.label 'Add image'
  = image_tag(@post.post_img_url) if @post.post_img?
  = f.file_field :post_img
  = f.hidden_field :post_img_cache

  .actions
  = f.submit

app/views/posts/edit.html.slim
h1 Editing post

= render 'form'

= link_to 'Show', @post 
|  || 
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts


- @posts.find_all do |post|
  | title:&nbsp
  strong = link_to post.title, post_path(post)
  | &nbsp tag:&nbsp
  strong = raw post.tag_list.map { |t| link_to t, posts_tags_path(t) }.join(', ')
  br

  br

br

- @tag_statistic.each do |tag_name, count|
  = link_to tag_name, posts_tags_path(tag_name)
  | &nbsp&nbsp
  = count
  br

= link_to 'New Post', new_post_path

br

app/views/posts/new.html.slim
h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
h3 Title:
u = @post.title
h3 Body: 
u = @post.body
br
br
= link_to 'Back', request.referer