config/routes.rb
Rails.application.routes.draw do
  resources :colorschemas

  resources :dotfiles

  resources :hacks
  get 'hacks_tags/:tag', to: 'hacks#index', as: :hacks_tags
  get 'hacks_vote/:id', to: 'hacks#vote', as: :hacks_vote

  devise_for :users
  resources :users
  get 'view_log', to: 'users#view_log', as: :log
  get 'view_plugins_list', to: 'users#view_plugins_list', as: :plugins_list
  post 'create_dotfile', to: 'users#create_dotfile', as: :create_dotfile

  resources :posts
  get 'posts_tags/:tag', to: 'posts#index', as: :posts_tags

  resources :plugins
  get 'plugins_tags/:tag', to: 'plugins#index', as: :plugins_tags
  get 'plugins_vote/:id', to: 'plugins#vote', as: :plugins_vote

  get 'search', to: 'search#search', as: :search
  match "/auth/:provider/callback" => "sessions#create", via: [:get]

  root 'users#index'

end

app/views/layouts/_navbar.html.erb
<%= link_to "Google", '/auth/google_oauth2' %>, <%= link_to "GitHub", "/auth/github" %>,  <%= link_to "Twitter", "/auth/twitter" %>, <%= link_to "Plugins", plugins_path %> || <%= link_to "Hacks", hacks_path %> || <%= link_to "Color-schemas", colorschemas_path %> || <%= link_to ".dotfiles", dotfiles_path %> || <%= link_to "Blog", posts_path %> || <%= link_to "Community" %> || <% if user_signed_in? %><%= link_to "Contacts", users_path %> || <%= link_to 'Log', log_path %><% end %> || <%= link_to 'View plugins list', plugins_list_path %> || <%= button_to 'Create dotfile',  create_dotfile_path %>

  <%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= search_field_tag(:q) %>
  <%= submit_tag("Search") %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<ul class="hmenu"> 
  <% if user_signed_in? %><h4> Logged as: <%= current_user.nickname %> <% end %>
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>

<header>
	<%= render "layouts/navbar" %>
</header>

<body>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>

<footer>
	<%= render "layouts/navbar" %>
</footer>
</html>